apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  # URL externa do ArgoCD (substitua pelo seu domínio)
  url: https://argocd.example.com/

  # Configuração do Dex para autenticação SSO
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    # Exemplo de integração SAML com Azure AD / Microsoft Entra ID
    - type: saml
      id: saml
      name: saml
      config:
        # Entity Issuer - URL do callback do ArgoCD
        entityIssuer: https://argocd.example.com/api/dex/callback

        # SSO URL do Azure AD (substitua YOUR-TENANT-ID pelo ID do seu tenant)
        ssoURL: https://login.microsoftonline.com/YOUR-TENANT-ID/saml2

        # Certificado público do provedor SAML (base64)
        # Obtenha este certificado no portal do Azure AD em:
        # Azure AD > Enterprise Applications > Sua App > Single sign-on > SAML Signing Certificate
        caData: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lKQUtF
          eExhYmJhYmJhTUEwR0NTcUdTSWIzRFFFQkN3VUFNQm94R0RBV0JnTlYKQkFNTUQyVjRZ
          VzF3YkdVdVkyOXRMbUp5TUI0WERUSXdNRGt4TlRFME1qQXdNRm9YRFRNd01Ea3hNelUw
          TWpBdwpNRm93R2pFWU1CWUdBMVVFQXd3UFpYaGhiWEJzWlM1amIyMHVZbkl3Z2dFaU1B
          MEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURFeGFtcGxlVGVzdENl
          cnRpZmljYXRlRGF0YUhlcmVFeGFtcGxlT25seQpGb3JUZXN0aW5nUHVycG9zZXNPbmx5
          RG9Ob3RVc2VJblByb2R1Y3Rpb25FeGFtcGxlQ2VydGlmaWNhdGUKRGF0YUhlcmVFeGFt
          cGxlT25seUZvclRlc3RpbmdQdXJwb3Nlc09ubHlEb05vdFVzZUluUHJvZHVjdGlvbgpF
          eGFtcGxlQ2VydGlmaWNhdGVEYXRhSGVyZUV4YW1wbGVPbmx5Rm9yVGVzdGluZ1B1cnBv
          c2VzT25seURvCk5vdFVzZUluUHJvZHVjdGlvbkV4YW1wbGVDZXJ0aWZpY2F0ZURhdGFI
          ZXJlRXhhbXBsZU9ubHlGb3JUZXN0aW5nClB1cnBvc2VzT25seURvTm90VXNlSW5Qcm9k
          dWN0aW9uRXhhbXBsZUNlcnRpZmljYXRlRGF0YUhlcmVFeGFtcGxlCk9ubHlGb3JUZXN0
          aW5nUHVycG9zZXNPbmx5RG9Ob3RVc2VJblByb2R1Y3Rpb24KLS0tLS1FTkQgQ0VSVElG
          SUNBVEUtLS0tLQo=

        # URL de redirecionamento após autenticação
        redirectURI: https://argocd.example.com/api/dex/callback

        # Atributos SAML para mapear usuário
        usernameAttr: email
        emailAttr: email
        groupsAttr: Group  # Atributo que contém os grupos do usuário
