apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  password: <<AZURE_PERSONAL_ACCESS_TOKEN>>
  url: <url>
  username: <username>
type: Opaque
